/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacote_Quiz;

import static Pacote_Quiz.frmQuiz.frmQuiz;

/**
 *
 * @author Natalia Miyuki Sakai
 */
public class frmGabarito extends javax.swing.JFrame {

    /**
     * Creates new form frmGabarito
     */
    public frmGabarito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rad1_4 = new javax.swing.JRadioButton();
        rad1_5 = new javax.swing.JRadioButton();
        rad1_6 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        rad2_4 = new javax.swing.JRadioButton();
        rad2_5 = new javax.swing.JRadioButton();
        rad2_6 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        rad3_4 = new javax.swing.JRadioButton();
        rad3_5 = new javax.swing.JRadioButton();
        rad3_6 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        rad4_4 = new javax.swing.JRadioButton();
        rad4_5 = new javax.swing.JRadioButton();
        rad4_6 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        rad5_4 = new javax.swing.JRadioButton();
        rad5_5 = new javax.swing.JRadioButton();
        rad5_6 = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        rad6_4 = new javax.swing.JRadioButton();
        rad6_5 = new javax.swing.JRadioButton();
        rad6_6 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        rad7_4 = new javax.swing.JRadioButton();
        rad7_5 = new javax.swing.JRadioButton();
        rad7_6 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        rad8_4 = new javax.swing.JRadioButton();
        rad8_5 = new javax.swing.JRadioButton();
        rad8_6 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        rad9_4 = new javax.swing.JRadioButton();
        rad9_5 = new javax.swing.JRadioButton();
        rad9_6 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        rad10_3 = new javax.swing.JRadioButton();
        rad10_4 = new javax.swing.JRadioButton();
        lbl1 = new javax.swing.JLabel();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gabarito");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GABARITO");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("1 - Quantos anos durou a Primeira Guerra Mundial? ");

        rad1_4.setText("6 anos");
        rad1_4.setEnabled(false);

        rad1_5.setText("5 anos");
        rad1_5.setEnabled(false);

        rad1_6.setSelected(true);
        rad1_6.setText("4 anos");
        rad1_6.setEnabled(false);

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("2 - Qual é o menor e o maior país do mundo?");

        rad2_4.setText("Mônaco e India");
        rad2_4.setEnabled(false);

        rad2_5.setSelected(true);
        rad2_5.setText("Vaticano e Russia");
        rad2_5.setEnabled(false);

        rad2_6.setText("San Marino e Austrália");
        rad2_6.setEnabled(false);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("3 - Qual é a estrela que fica mais próxima do planeta Terra?");

        rad3_4.setText("Lua");
        rad3_4.setEnabled(false);

        rad3_5.setSelected(true);
        rad3_5.setText("Sol");
        rad3_5.setEnabled(false);

        rad3_6.setText("Alfa Centauri");
        rad3_6.setEnabled(false);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("4 - Quantos ossos tem o corpo humano de uma pessoa adulta?");

        rad4_4.setText("354");
        rad4_4.setEnabled(false);

        rad4_5.setSelected(true);
        rad4_5.setText("206");
        rad4_5.setEnabled(false);

        rad4_6.setText("198");
        rad4_6.setEnabled(false);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("5 - Em qual cidade brasileira está o Rio Tietê?");

        rad5_4.setSelected(true);
        rad5_4.setText("São Paulo");
        rad5_4.setEnabled(false);

        rad5_5.setText("Bauru");
        rad5_5.setEnabled(false);

        rad5_6.setText("Belo Horizonte");
        rad5_6.setEnabled(false);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("6 - Se a filha de Tereza é a filha da mãe da minha filha, o que eu sou de Tereza?");

        rad6_4.setText("Mãe");
        rad6_4.setEnabled(false);

        rad6_5.setSelected(true);
        rad6_5.setText("Avó");
        rad6_5.setEnabled(false);

        rad6_6.setText("Filha");
        rad6_6.setEnabled(false);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("7 - Qual estação do ano que antecede a Primaveira?");

        rad7_4.setText("Verão");
        rad7_4.setEnabled(false);

        rad7_5.setSelected(true);
        rad7_5.setText("Inverno");
        rad7_5.setEnabled(false);

        rad7_6.setText("Outono");
        rad7_6.setEnabled(false);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("8 - Quem foi o físico que criou a Lei da gravitação universal?");

        rad8_4.setText("Albert Einstein");
        rad8_4.setEnabled(false);

        rad8_5.setText("Thomas Edson");
        rad8_5.setEnabled(false);

        rad8_6.setSelected(true);
        rad8_6.setText("Isaac Newton");
        rad8_6.setEnabled(false);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("9 - O que era Édipo Rei?");

        rad9_4.setText("Um ator do teatro isabelino");
        rad9_4.setEnabled(false);

        rad9_5.setText("Um guerreiro de Tróia");
        rad9_5.setEnabled(false);

        rad9_6.setSelected(true);
        rad9_6.setText("Uma tragédia grega");
        rad9_6.setContentAreaFilled(false);
        rad9_6.setEnabled(false);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("10 - (BÔNUS) Qual é a melhor linguagem de programação?");

        rad10_3.setSelected(true);
        rad10_3.setText("JAVA");
        rad10_3.setEnabled(false);

        rad10_4.setText("C#");
        rad10_4.setEnabled(false);

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rad1_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rad1_5)
                        .addGap(66, 66, 66)
                        .addComponent(rad1_6)
                        .addGap(69, 69, 69))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(rad2_6)
                                .addGap(18, 18, 18)
                                .addComponent(rad2_4)
                                .addGap(26, 26, 26)
                                .addComponent(rad2_5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rad8_5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rad8_4)
                                        .addGap(27, 27, 27)
                                        .addComponent(rad8_6)
                                        .addGap(37, 37, 37))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rad7_4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rad7_5)
                                        .addGap(56, 56, 56)
                                        .addComponent(rad7_6)
                                        .addGap(68, 68, 68))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rad6_4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rad6_5)
                                        .addGap(75, 75, 75)
                                        .addComponent(rad6_6)
                                        .addGap(82, 82, 82))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rad5_4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rad5_6)
                                        .addGap(26, 26, 26)
                                        .addComponent(rad5_5)
                                        .addGap(76, 76, 76))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rad4_4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rad4_5)
                                        .addGap(76, 76, 76)
                                        .addComponent(rad4_6)
                                        .addGap(87, 87, 87))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rad9_4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rad9_5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rad9_6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rad3_4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rad3_5)
                                        .addGap(84, 84, 84)
                                        .addComponent(rad3_6)
                                        .addGap(39, 39, 39))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(265, 265, 265)
                                        .addComponent(voltar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rad10_3)
                                        .addGap(106, 106, 106)
                                        .addComponent(rad10_4)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lbl1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl1)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad1_5)
                            .addComponent(rad1_6)
                            .addComponent(rad1_4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad2_4)
                            .addComponent(rad2_5)
                            .addComponent(rad2_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad3_4)
                            .addComponent(rad3_5)
                            .addComponent(rad3_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad4_4)
                            .addComponent(rad4_5)
                            .addComponent(rad4_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad5_4)
                            .addComponent(rad5_6)
                            .addComponent(rad5_5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad6_4)
                            .addComponent(rad6_5)
                            .addComponent(rad6_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad7_4)
                            .addComponent(rad7_5)
                            .addComponent(rad7_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad8_5)
                            .addComponent(rad8_4)
                            .addComponent(rad8_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad9_4)
                            .addComponent(rad9_5)
                            .addComponent(rad9_6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rad10_3)
                            .addComponent(rad10_4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(voltar)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        this.hide();
        frmQuiz.show();
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGabarito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGabarito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JRadioButton rad10_3;
    private javax.swing.JRadioButton rad10_4;
    private javax.swing.JRadioButton rad1_4;
    private javax.swing.JRadioButton rad1_5;
    private javax.swing.JRadioButton rad1_6;
    private javax.swing.JRadioButton rad2_4;
    private javax.swing.JRadioButton rad2_5;
    private javax.swing.JRadioButton rad2_6;
    private javax.swing.JRadioButton rad3_4;
    private javax.swing.JRadioButton rad3_5;
    private javax.swing.JRadioButton rad3_6;
    private javax.swing.JRadioButton rad4_4;
    private javax.swing.JRadioButton rad4_5;
    private javax.swing.JRadioButton rad4_6;
    private javax.swing.JRadioButton rad5_4;
    private javax.swing.JRadioButton rad5_5;
    private javax.swing.JRadioButton rad5_6;
    private javax.swing.JRadioButton rad6_4;
    private javax.swing.JRadioButton rad6_5;
    private javax.swing.JRadioButton rad6_6;
    private javax.swing.JRadioButton rad7_4;
    private javax.swing.JRadioButton rad7_5;
    private javax.swing.JRadioButton rad7_6;
    private javax.swing.JRadioButton rad8_4;
    private javax.swing.JRadioButton rad8_5;
    private javax.swing.JRadioButton rad8_6;
    private javax.swing.JRadioButton rad9_4;
    private javax.swing.JRadioButton rad9_5;
    private javax.swing.JRadioButton rad9_6;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
