/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacote_Quiz;

import javax.swing.Action;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalia Miyuki Sakai
 */
public class frmQuiz extends javax.swing.JFrame {

    static public frmQuiz frmQuiz;
    static public frmGabarito frmGabarito;
    
    public frmQuiz() {
        frmGabarito = new frmGabarito();
        frmGabarito.setVisible(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group1 = new javax.swing.ButtonGroup();
        group2 = new javax.swing.ButtonGroup();
        group3 = new javax.swing.ButtonGroup();
        group4 = new javax.swing.ButtonGroup();
        group5 = new javax.swing.ButtonGroup();
        group6 = new javax.swing.ButtonGroup();
        group7 = new javax.swing.ButtonGroup();
        group8 = new javax.swing.ButtonGroup();
        group9 = new javax.swing.ButtonGroup();
        group10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rad1_1 = new javax.swing.JRadioButton();
        rad1_2 = new javax.swing.JRadioButton();
        rad1_3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rad2_1 = new javax.swing.JRadioButton();
        rad2_2 = new javax.swing.JRadioButton();
        rad2_3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rad3_1 = new javax.swing.JRadioButton();
        rad3_2 = new javax.swing.JRadioButton();
        rad3_3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        rad4_1 = new javax.swing.JRadioButton();
        rad4_2 = new javax.swing.JRadioButton();
        rad4_3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rad5_1 = new javax.swing.JRadioButton();
        rad5_3 = new javax.swing.JRadioButton();
        rad5_2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rad6_1 = new javax.swing.JRadioButton();
        rad6_2 = new javax.swing.JRadioButton();
        rad6_3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rad7_1 = new javax.swing.JRadioButton();
        rad7_2 = new javax.swing.JRadioButton();
        rad7_3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rad8_2 = new javax.swing.JRadioButton();
        rad8_1 = new javax.swing.JRadioButton();
        rad8_3 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rad9_1 = new javax.swing.JRadioButton();
        rad9_2 = new javax.swing.JRadioButton();
        rad9_3 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        rad10_1 = new javax.swing.JRadioButton();
        rad10_2 = new javax.swing.JRadioButton();
        sair = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        gabarito = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        novo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONHECIMENTOS GERAIS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 22, 415, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("1 - Quantos anos durou a Primeira Guerra Mundial? ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 54, 415, -1));

        group1.add(rad1_1);
        rad1_1.setText("6 anos");
        rad1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rad1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 70, -1, -1));

        group1.add(rad1_2);
        rad1_2.setText("5 anos");
        rad1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rad1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 70, -1, -1));

        group1.add(rad1_3);
        rad1_3.setText("4 anos");
        rad1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad1_3ActionPerformed(evt);
            }
        });
        jPanel1.add(rad1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 70, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("2 - Qual é o menor e o maior país do mundo?");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 95, 282, -1));

        group2.add(rad2_1);
        rad2_1.setText("Mônaco e India");
        rad2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rad2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 111, -1, -1));

        group2.add(rad2_2);
        rad2_2.setText("Vaticano e Russia");
        rad2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rad2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 111, -1, -1));

        group2.add(rad2_3);
        rad2_3.setText("San Marino e Austrália");
        rad2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad2_3ActionPerformed(evt);
            }
        });
        jPanel1.add(rad2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 111, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("3 - Qual é a estrela que fica mais próxima do planeta Terra?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 136, 415, -1));

        group3.add(rad3_1);
        rad3_1.setText("Lua");
        rad3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad3_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rad3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 152, -1, -1));

        group3.add(rad3_2);
        rad3_2.setText("Sol");
        rad3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad3_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rad3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 152, -1, -1));

        group3.add(rad3_3);
        rad3_3.setText("Alfa Centauri");
        rad3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad3_3ActionPerformed(evt);
            }
        });
        jPanel1.add(rad3_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 152, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("4 - Quantos ossos tem o corpo humano de uma pessoa adulta?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 177, 415, -1));

        group4.add(rad4_1);
        rad4_1.setText("354");
        rad4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad4_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rad4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 193, -1, -1));

        group4.add(rad4_2);
        rad4_2.setText("206");
        rad4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad4_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rad4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 193, -1, -1));

        group4.add(rad4_3);
        rad4_3.setText("198");
        rad4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad4_3ActionPerformed(evt);
            }
        });
        jPanel1.add(rad4_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 193, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("5 - Em qual cidade brasileira está o Rio Tietê?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 218, 415, -1));

        group5.add(rad5_1);
        rad5_1.setText("São Paulo");
        rad5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad5_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rad5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 234, -1, -1));

        group5.add(rad5_3);
        rad5_3.setText("Bauru");
        rad5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad5_3ActionPerformed(evt);
            }
        });
        jPanel1.add(rad5_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 234, -1, -1));

        group5.add(rad5_2);
        rad5_2.setText("Belo Horizonte");
        rad5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad5_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rad5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 234, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("6 - Se a filha de Tereza é a filha da mãe da minha filha, o que eu sou de Tereza?");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 259, 415, -1));

        group6.add(rad6_1);
        rad6_1.setText("Mãe");
        rad6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad6_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rad6_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 275, -1, -1));

        group6.add(rad6_2);
        rad6_2.setText("Avó");
        rad6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad6_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rad6_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 275, -1, -1));

        group6.add(rad6_3);
        rad6_3.setText("Filha");
        rad6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad6_3ActionPerformed(evt);
            }
        });
        jPanel1.add(rad6_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 275, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("7 - Qual estação do ano que antecede a Primaveira?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 300, 415, -1));

        group7.add(rad7_1);
        rad7_1.setText("Verão");
        rad7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad7_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rad7_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 316, -1, -1));

        group7.add(rad7_2);
        rad7_2.setText("Inverno");
        rad7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad7_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rad7_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 316, -1, -1));

        group7.add(rad7_3);
        rad7_3.setText("Outono");
        rad7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad7_3ActionPerformed(evt);
            }
        });
        jPanel1.add(rad7_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 316, -1, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("8 - Quem foi o físico que criou a Lei da gravitação universal?");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 341, 415, -1));

        group8.add(rad8_2);
        rad8_2.setText("Albert Einstein");
        rad8_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad8_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rad8_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 357, -1, -1));

        group8.add(rad8_1);
        rad8_1.setText("Thomas Edson");
        rad8_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad8_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rad8_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 357, -1, -1));

        group8.add(rad8_3);
        rad8_3.setText("Isaac Newton");
        rad8_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad8_3ActionPerformed(evt);
            }
        });
        jPanel1.add(rad8_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 357, -1, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("9 - O que era Édipo Rei?");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 382, 415, -1));

        group9.add(rad9_1);
        rad9_1.setText("Um ator do teatro isabelino");
        rad9_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad9_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rad9_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 398, -1, -1));

        group9.add(rad9_2);
        rad9_2.setText("Um guerreiro de Tróia");
        rad9_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad9_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rad9_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 398, -1, -1));

        group9.add(rad9_3);
        rad9_3.setText("Uma tragédia grega");
        rad9_3.setContentAreaFilled(false);
        rad9_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad9_3ActionPerformed(evt);
            }
        });
        jPanel1.add(rad9_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 398, -1, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("10 - (BÔNUS) Qual é a melhor linguagem de programação?");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 423, 415, -1));

        group10.add(rad10_1);
        rad10_1.setText("JAVA");
        rad10_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad10_1ActionPerformed(evt);
            }
        });
        jPanel1.add(rad10_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 439, -1, -1));

        group10.add(rad10_2);
        rad10_2.setText("C#");
        rad10_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad10_2ActionPerformed(evt);
            }
        });
        jPanel1.add(rad10_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 439, -1, -1));

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jPanel1.add(sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 496, -1, -1));

        resultado.setText("Resultado");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        jPanel1.add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 496, -1, -1));

        gabarito.setText("Gabarito");
        gabarito.setEnabled(false);
        gabarito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gabaritoActionPerformed(evt);
            }
        });
        jPanel1.add(gabarito, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 496, -1, -1));

        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 464, 76, 26));

        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });
        jPanel1.add(novo, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 496, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 430, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        // TODO add your handling code here:
        int resposta= JOptionPane.showConfirmDialog(null, " Deseja realmente sair?","Quiz", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    int checar1=0;
    int checar2=0;
    int checar3=0;
    int checar4=0;
    int checar5=0;
    int checar6=0;
    int checar7=0;
    int checar8=0;
    int checar9=0;
    int checar10=0;
    
    int resposta = 0;
    
    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        // TODO add your handling code here:
        if(checar1 == 0 || checar2 == 0 || checar3 == 0 || checar4 == 0 || checar5 == 0 || checar6 == 0 || checar7 == 0 || checar8 == 0 || checar9 == 0 || checar10 == 0)
        {
            JOptionPane.showMessageDialog(null, "Você deve selecionar uma opção!", "Quiz", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            gabarito.setEnabled(true);
            resultado.setEnabled(false);
            lbl.setText(String.valueOf(resposta)+" / 10");
        }

    }//GEN-LAST:event_resultadoActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed
        // TODO add your handling code here:
        group1.clearSelection();
        group2.clearSelection();
        group3.clearSelection();
        group4.clearSelection();
        group5.clearSelection();
        group6.clearSelection();
        group7.clearSelection();
        group8.clearSelection();
        group9.clearSelection();
        group10.clearSelection();
        
        checar1=0;
        checar2=0;
        checar3=0;
        checar4=0;
        checar5=0;
        checar6=0;
        checar7=0;
        checar8=0;
        checar9=0;
        checar10=0;
        
        lbl.setText("");
        
        resposta = 0;
        
        gabarito.setEnabled(false);
        resultado.setEnabled(true);
    }//GEN-LAST:event_novoActionPerformed

    private void gabaritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gabaritoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.hide();
        frmGabarito.show();
    }//GEN-LAST:event_gabaritoActionPerformed

    private void rad1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1_1ActionPerformed
        // TODO add your handling code here:
        checar1 = 1;
    }//GEN-LAST:event_rad1_1ActionPerformed

    private void rad1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1_2ActionPerformed
        // TODO add your handling code here:
        checar1 = 2;
    }//GEN-LAST:event_rad1_2ActionPerformed

    private void rad1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad1_3ActionPerformed
        // TODO add your handling code here:
        checar1 = 3;
        resposta++;
    }//GEN-LAST:event_rad1_3ActionPerformed

    private void rad2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2_1ActionPerformed
        // TODO add your handling code here:
        checar2 = 1;
    }//GEN-LAST:event_rad2_1ActionPerformed

    private void rad2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2_2ActionPerformed
        // TODO add your handling code here:
        checar2 = 2;
        resposta++;
    }//GEN-LAST:event_rad2_2ActionPerformed

    private void rad2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad2_3ActionPerformed
        // TODO add your handling code here:
        checar2 = 3;
    }//GEN-LAST:event_rad2_3ActionPerformed

    private void rad3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad3_1ActionPerformed
        // TODO add your handling code here:
        checar3 = 1;
    }//GEN-LAST:event_rad3_1ActionPerformed

    private void rad3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad3_2ActionPerformed
        // TODO add your handling code here:
        checar3 = 2;
        resposta++;
    }//GEN-LAST:event_rad3_2ActionPerformed

    private void rad3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad3_3ActionPerformed
        // TODO add your handling code here:
        checar3 = 3;
    }//GEN-LAST:event_rad3_3ActionPerformed

    private void rad4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad4_1ActionPerformed
        // TODO add your handling code here:
        checar4 = 1;
    }//GEN-LAST:event_rad4_1ActionPerformed

    private void rad4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad4_2ActionPerformed
        // TODO add your handling code here:
        checar4 = 2;
        resposta++;
    }//GEN-LAST:event_rad4_2ActionPerformed

    private void rad4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad4_3ActionPerformed
        // TODO add your handling code here:
        checar4 = 3;
    }//GEN-LAST:event_rad4_3ActionPerformed

    private void rad5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad5_1ActionPerformed
        // TODO add your handling code here:
        checar5 = 1;
        resposta++;
    }//GEN-LAST:event_rad5_1ActionPerformed

    private void rad5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad5_2ActionPerformed
        // TODO add your handling code here:
        checar5 = 2;
    }//GEN-LAST:event_rad5_2ActionPerformed

    private void rad5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad5_3ActionPerformed
        // TODO add your handling code here:
        checar5 = 3;
    }//GEN-LAST:event_rad5_3ActionPerformed

    private void rad6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad6_1ActionPerformed
        // TODO add your handling code here:
        checar6 = 1;
    }//GEN-LAST:event_rad6_1ActionPerformed

    private void rad6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad6_2ActionPerformed
        // TODO add your handling code here:
        checar6 = 2;
        resposta++;
    }//GEN-LAST:event_rad6_2ActionPerformed

    private void rad6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad6_3ActionPerformed
        // TODO add your handling code here:
        checar6 = 3;
    }//GEN-LAST:event_rad6_3ActionPerformed

    private void rad7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad7_1ActionPerformed
        // TODO add your handling code here:
        checar7 = 1;
    }//GEN-LAST:event_rad7_1ActionPerformed

    private void rad7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad7_2ActionPerformed
        // TODO add your handling code here:
        checar7 = 2;
        resposta++;
    }//GEN-LAST:event_rad7_2ActionPerformed

    private void rad7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad7_3ActionPerformed
        // TODO add your handling code here:
        checar7 = 3;
    }//GEN-LAST:event_rad7_3ActionPerformed

    private void rad8_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad8_1ActionPerformed
        // TODO add your handling code here:
        checar8 = 1;
    }//GEN-LAST:event_rad8_1ActionPerformed

    private void rad8_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad8_2ActionPerformed
        // TODO add your handling code here:
        checar8 = 2;
    }//GEN-LAST:event_rad8_2ActionPerformed

    private void rad8_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad8_3ActionPerformed
        // TODO add your handling code here:
        checar8 = 3;
        resposta++;
    }//GEN-LAST:event_rad8_3ActionPerformed

    private void rad9_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad9_1ActionPerformed
        // TODO add your handling code here:
        checar9 = 1;
    }//GEN-LAST:event_rad9_1ActionPerformed

    private void rad9_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad9_2ActionPerformed
        // TODO add your handling code here:
        checar9 = 2;
    }//GEN-LAST:event_rad9_2ActionPerformed

    private void rad9_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad9_3ActionPerformed
        // TODO add your handling code here:
        checar9 = 3;
        resposta++;
    }//GEN-LAST:event_rad9_3ActionPerformed

    private void rad10_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad10_1ActionPerformed
        // TODO add your handling code here:
        checar10 = 1;
        resposta++;
    }//GEN-LAST:event_rad10_1ActionPerformed

    private void rad10_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad10_2ActionPerformed
        // TODO add your handling code here:
        checar10 = 2;
    }//GEN-LAST:event_rad10_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmQuiz = new frmQuiz();
                frmQuiz.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gabarito;
    private javax.swing.ButtonGroup group1;
    private javax.swing.ButtonGroup group10;
    private javax.swing.ButtonGroup group2;
    private javax.swing.ButtonGroup group3;
    private javax.swing.ButtonGroup group4;
    private javax.swing.ButtonGroup group5;
    private javax.swing.ButtonGroup group6;
    private javax.swing.ButtonGroup group7;
    private javax.swing.ButtonGroup group8;
    private javax.swing.ButtonGroup group9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JButton novo;
    private javax.swing.JRadioButton rad10_1;
    private javax.swing.JRadioButton rad10_2;
    private javax.swing.JRadioButton rad1_1;
    private javax.swing.JRadioButton rad1_2;
    private javax.swing.JRadioButton rad1_3;
    private javax.swing.JRadioButton rad2_1;
    private javax.swing.JRadioButton rad2_2;
    private javax.swing.JRadioButton rad2_3;
    private javax.swing.JRadioButton rad3_1;
    private javax.swing.JRadioButton rad3_2;
    private javax.swing.JRadioButton rad3_3;
    private javax.swing.JRadioButton rad4_1;
    private javax.swing.JRadioButton rad4_2;
    private javax.swing.JRadioButton rad4_3;
    private javax.swing.JRadioButton rad5_1;
    private javax.swing.JRadioButton rad5_2;
    private javax.swing.JRadioButton rad5_3;
    private javax.swing.JRadioButton rad6_1;
    private javax.swing.JRadioButton rad6_2;
    private javax.swing.JRadioButton rad6_3;
    private javax.swing.JRadioButton rad7_1;
    private javax.swing.JRadioButton rad7_2;
    private javax.swing.JRadioButton rad7_3;
    private javax.swing.JRadioButton rad8_1;
    private javax.swing.JRadioButton rad8_2;
    private javax.swing.JRadioButton rad8_3;
    private javax.swing.JRadioButton rad9_1;
    private javax.swing.JRadioButton rad9_2;
    private javax.swing.JRadioButton rad9_3;
    private javax.swing.JButton resultado;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
