/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pacote_Jogo_Animais;

import javax.swing.JOptionPane;

/**
 *
 * @author Yasmin
 */
public class frmJogo_Animais extends javax.swing.JFrame {

    /**
     * Creates new form frmJogo_Animais
     */
    static public frmJogo_Animais frmJogo_Animais;
    
    public frmJogo_Animais() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl.setText("Jogo dos Animais");

        btnNovo.setText("Jogar Novamente");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addGap(39, 39, 39)
                        .addComponent(btnSair))
                    .addComponent(lbl))
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbl)
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnNovo))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void game ()
    {
         this.setVisible(false);
        
        Object[] ValoresPossiveis = {"Mamífero","Aves","Réptil"};
        Object[] ValoresPossiveisM = {"Quadrúpede","Bípede","Voador","Aquático"};
        Object[] ValoresPossiveisA = {"Não voadora","Nadadora"};
        Object[] ValoresPossiveisR = {"Com casco","Carnívoro","Sem patas"};
        Object[] ValoresPossiveisQua = {"Carnívoro","Herbívoro"};
        Object[] ValoresPossiveisBip = {"Onívoro","Frutífero"};
        Object[] ValoresPossiveisNao = {"Tropical","Polar"};
        Object ValorSelecionado1, ValorSelecionado2, ValorSelecionado3;
        ValorSelecionado1 = JOptionPane.showInputDialog( null, "Escolha uma opção" , "Game" , JOptionPane.INFORMATION_MESSAGE,null,ValoresPossiveis,ValoresPossiveis[0]);
        if (ValorSelecionado1 == "Mamífero")
        {
            
            ValorSelecionado2 = JOptionPane.showInputDialog( null, "Escolha uma opção" , "Game" , JOptionPane.INFORMATION_MESSAGE,null,ValoresPossiveisM,ValoresPossiveisM[0]);
            
            if (ValorSelecionado2 == "Quadrúpede")
            {
                ValorSelecionado3 = JOptionPane.showInputDialog( null, "Escolha uma opção" , "Game" , JOptionPane.INFORMATION_MESSAGE,null,ValoresPossiveisQua,ValoresPossiveisQua[0]);
                
                if (ValorSelecionado3 == "Carnívoro")
                {
                    JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Leão","Game",JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(true);
                }
                else if (ValorSelecionado3 == "Herbívoro")
                {
                    JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Cavalo","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
                }
            }
            else if (ValorSelecionado2 == "Bípede")
            {
                ValorSelecionado3 = JOptionPane.showInputDialog( null, "Escolha uma opção" , "Game" , JOptionPane.INFORMATION_MESSAGE,null,ValoresPossiveisBip,ValoresPossiveisBip[0]);
                
                if (ValorSelecionado3 == "Onívoro")
                {
                    JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Homem","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
                }
                else if (ValorSelecionado3 == "Frutífero")
                {
                    JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Macaco","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
                }
            }
            else if (ValorSelecionado2 == "Voador")
            {
                JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Morcego","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
            }
            else if (ValorSelecionado2 == "Aquático")
            {
                JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Baleia","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
            }
        }
        else if (ValorSelecionado1 == "Aves")
        {
            ValorSelecionado2 = JOptionPane.showInputDialog( null, "Escolha uma opção" , "Game" , JOptionPane.INFORMATION_MESSAGE,null,ValoresPossiveisA,ValoresPossiveisA[0]);
            
            if (ValorSelecionado2 == "Não voadora")
            {
                ValorSelecionado3 = JOptionPane.showInputDialog( null, "Escolha uma opção" , "Game" , JOptionPane.INFORMATION_MESSAGE,null,ValoresPossiveisNao,ValoresPossiveisNao[0]);
            
                if (ValorSelecionado3 == "Tropical")
                {
                    JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Avestruz","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
                }
                else if (ValorSelecionado3 == "Polar")
                {
                    JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Pinguim","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
                }
            }
            else if (ValorSelecionado2 == "Nadadora")
            {
                JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Pato","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
            }
        }
        else if (ValorSelecionado1 == "Réptil")
        {
            ValorSelecionado2 = JOptionPane.showInputDialog( null, "Escolha uma opção" , "Game" , JOptionPane.INFORMATION_MESSAGE,null,ValoresPossiveisR,ValoresPossiveisR[0]);
            
            if (ValorSelecionado2 == "Com casco")
            {
                JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Tartaruga","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
            }
            else if (ValorSelecionado2 == "Carnívoro")
            {
                JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Crocodilo","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
            }
            else if (ValorSelecionado2 == "Sem patas")
            {
                JOptionPane.showMessageDialog(null, "Animal com características relacionadas: Cobra","Game",JOptionPane.INFORMATION_MESSAGE); 
                    this.setVisible(true);
            }
        }
    }
            
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        game ();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formWindowActivated

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
  
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        game ();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        int resposta= JOptionPane.showConfirmDialog(null, " Deseja realmente sair?","Game", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (resposta == JOptionPane.YES_OPTION)
            System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJogo_Animais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJogo_Animais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJogo_Animais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJogo_Animais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJogo_Animais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables
}
