/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PacoteSangue;

import javax.swing.JOptionPane;
/**
 *
 * @author Yasmin
 */
public class FrmSangue extends javax.swing.JFrame {

    /**
     * Creates new form FrmSangue
     */
    public FrmSangue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoSanguineo = new javax.swing.ButtonGroup();
        fatorRH = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTipoSO = new javax.swing.JRadioButton();
        btnTipoSA = new javax.swing.JRadioButton();
        btnTipoSAB = new javax.swing.JRadioButton();
        btnTipoSB = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnNegativo = new javax.swing.JRadioButton();
        btnPositivo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ckbRecepOp = new javax.swing.JCheckBox();
        ckbRecepAp = new javax.swing.JCheckBox();
        ckbRecepABp = new javax.swing.JCheckBox();
        ckbRecepBp = new javax.swing.JCheckBox();
        ckbRecepBn = new javax.swing.JCheckBox();
        ckbRecepABn = new javax.swing.JCheckBox();
        ckbRecepAn = new javax.swing.JCheckBox();
        ckbRecepOn = new javax.swing.JCheckBox();
        btnValidar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doação de Sangue");

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Selecione seu tipo sanguíneo:");

        tipoSanguineo.add(btnTipoSO);
        btnTipoSO.setText("O");
        btnTipoSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoSOActionPerformed(evt);
            }
        });

        tipoSanguineo.add(btnTipoSA);
        btnTipoSA.setText("A");
        btnTipoSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoSAActionPerformed(evt);
            }
        });

        tipoSanguineo.add(btnTipoSAB);
        btnTipoSAB.setText("AB");
        btnTipoSAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoSABActionPerformed(evt);
            }
        });

        tipoSanguineo.add(btnTipoSB);
        btnTipoSB.setText("B");
        btnTipoSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoSBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTipoSO)
                        .addGap(41, 41, 41)
                        .addComponent(btnTipoSA)
                        .addGap(51, 51, 51)
                        .addComponent(btnTipoSB)
                        .addGap(44, 44, 44)
                        .addComponent(btnTipoSAB)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTipoSO)
                    .addComponent(btnTipoSA)
                    .addComponent(btnTipoSAB)
                    .addComponent(btnTipoSB))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tipo Sanguíneo", jPanel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Selecione seu fator RH:");

        fatorRH.add(btnNegativo);
        btnNegativo.setText("Negativo");

        fatorRH.add(btnPositivo);
        btnPositivo.setText("Positivo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(btnPositivo)
                .addGap(72, 72, 72)
                .addComponent(btnNegativo)
                .addGap(87, 87, 87))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPositivo)
                    .addComponent(btnNegativo))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fator RH", jPanel2);

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Selecione todos os seus possíveis receptores:");

        ckbRecepOp.setText("O+");

        ckbRecepAp.setText("A+");

        ckbRecepABp.setText("AB+");

        ckbRecepBp.setText("B+");

        ckbRecepBn.setText("B-");

        ckbRecepABn.setText("AB-");

        ckbRecepAn.setText("A-");

        ckbRecepOn.setText("O-");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbRecepBp)
                            .addComponent(ckbRecepABp)
                            .addComponent(ckbRecepAp)
                            .addComponent(ckbRecepOp))
                        .addGap(116, 116, 116)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ckbRecepAn)
                            .addComponent(ckbRecepBn)
                            .addComponent(ckbRecepABn)
                            .addComponent(ckbRecepOn))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbRecepOp)
                    .addComponent(ckbRecepOn))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbRecepBn)
                            .addComponent(ckbRecepBp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbRecepABn)
                            .addComponent(ckbRecepABp))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbRecepAp)
                            .addComponent(ckbRecepAn))
                        .addGap(73, 73, 73))))
        );

        jTabbedPane1.addTab("Possíveis Receptores", jPanel3);

        btnValidar.setText("Validar Doação");
        btnValidar.setEnabled(false);
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnValidar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpar)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValidar)
                    .addComponent(btnLimpar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Tipo Sanguíneo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        btnValidar.setEnabled(false);
        tipoSanguineo.clearSelection();
        fatorRH.clearSelection();
        ckbRecepABn.setSelected(false);
        ckbRecepAn.setSelected(false);
        ckbRecepBn.setSelected(false);
        ckbRecepOn.setSelected(false);
        ckbRecepABp.setSelected(false);
        ckbRecepAp.setSelected(false);
        ckbRecepBp.setSelected(false);
        ckbRecepOp.setSelected(false);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        // TODO add your handling code here:
        if (btnPositivo.isSelected() || btnNegativo.isSelected())
        {
            if (ckbRecepABn.isSelected() || ckbRecepABp.isSelected() || ckbRecepAn.isSelected() || ckbRecepAp.isSelected() || ckbRecepBn.isSelected() || ckbRecepBp.isSelected() || ckbRecepBp.isSelected() || ckbRecepOn.isSelected() || ckbRecepOp.isSelected())
            {
                if(btnTipoSA.isSelected())
                {
                    if(btnPositivo.isSelected())
                    {
                        if (ckbRecepABn.isSelected() || ckbRecepAn.isSelected() || ckbRecepBp.isSelected() || ckbRecepBp.isSelected() || ckbRecepOn.isSelected() || ckbRecepOp.isSelected())
                        {
                            JOptionPane.showMessageDialog(null, "Assim você matará alguém!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Doação Válida, salvará vidas!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                    else if(btnNegativo.isSelected())
                    {
                        if (ckbRecepBn.isSelected() || ckbRecepBp.isSelected() || ckbRecepOn.isSelected() || ckbRecepOp.isSelected())
                        {
                            JOptionPane.showMessageDialog(null, "Assim você matará alguém!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Doação Válida, salvará vidas!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
                else if(btnTipoSB.isSelected())
                {
                    if(btnPositivo.isSelected())
                    {
                        if (ckbRecepABn.isSelected() || ckbRecepAn.isSelected() || ckbRecepAp.isSelected() || ckbRecepBn.isSelected() || ckbRecepOn.isSelected() || ckbRecepOp.isSelected())
                        {
                            JOptionPane.showMessageDialog(null, "Assim você matará alguém!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Doação Válida, salvará vidas!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                    else if(btnNegativo.isSelected())
                    {
                        if (ckbRecepAn.isSelected() || ckbRecepAp.isSelected() || ckbRecepOn.isSelected() || ckbRecepOp.isSelected())
                        {
                            JOptionPane.showMessageDialog(null, "Assim você matará alguém!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Doação Válida, salvará vidas!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
                else if(btnTipoSAB.isSelected())
                {
                    if(btnPositivo.isSelected())
                    {
                        if (ckbRecepABn.isSelected() || ckbRecepAn.isSelected() || ckbRecepAp.isSelected() || ckbRecepBn.isSelected() || ckbRecepBp.isSelected() || ckbRecepOn.isSelected() || ckbRecepOp.isSelected())
                        {
                            JOptionPane.showMessageDialog(null, "Assim você matará alguém!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Doação Válida, salvará vidas!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                    else if(btnNegativo.isSelected())
                    {
                        if (ckbRecepAn.isSelected() || ckbRecepAp.isSelected() || ckbRecepBn.isSelected() || ckbRecepBp.isSelected() || ckbRecepOn.isSelected() || ckbRecepOp.isSelected())
                        {
                            JOptionPane.showMessageDialog(null, "Assim você matará alguém!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Doação Válida, salvará vidas!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                }
                else if(btnTipoSO.isSelected())
                {
                    if(btnPositivo.isSelected())
                    {
                        if (ckbRecepABn.isSelected()|| ckbRecepAn.isSelected() || ckbRecepBn.isSelected() || ckbRecepOn.isSelected())
                        {
                            JOptionPane.showMessageDialog(null, "Assim você matará alguém!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(null, "Doação Válida, salvará vidas!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                    else if(btnNegativo.isSelected())
                    {
                        JOptionPane.showMessageDialog(null, "Doação Válida, salvará vidas!!!", "Validação", JOptionPane.INFORMATION_MESSAGE);
                    }
                }
                btnValidar.setEnabled(false);
                btnLimparActionPerformed(evt);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Você deve selecionar os receptores !!!", "Doação", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Você deve selecionar um Fator RH !!!", "Doação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnTipoSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoSOActionPerformed
        // TODO add your handling code here:
        btnValidar.setEnabled(true);
    }//GEN-LAST:event_btnTipoSOActionPerformed

    private void btnTipoSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoSAActionPerformed
        // TODO add your handling code here:
        btnValidar.setEnabled(true);
    }//GEN-LAST:event_btnTipoSAActionPerformed

    private void btnTipoSABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoSABActionPerformed
        // TODO add your handling code here:
        btnValidar.setEnabled(true);
    }//GEN-LAST:event_btnTipoSABActionPerformed

    private void btnTipoSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoSBActionPerformed
        // TODO add your handling code here:
        btnValidar.setEnabled(true);
    }//GEN-LAST:event_btnTipoSBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSangue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSangue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSangue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSangue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSangue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JRadioButton btnNegativo;
    private javax.swing.JRadioButton btnPositivo;
    private javax.swing.JRadioButton btnTipoSA;
    private javax.swing.JRadioButton btnTipoSAB;
    private javax.swing.JRadioButton btnTipoSB;
    private javax.swing.JRadioButton btnTipoSO;
    private javax.swing.JButton btnValidar;
    private javax.swing.JCheckBox ckbRecepABn;
    private javax.swing.JCheckBox ckbRecepABp;
    private javax.swing.JCheckBox ckbRecepAn;
    private javax.swing.JCheckBox ckbRecepAp;
    private javax.swing.JCheckBox ckbRecepBn;
    private javax.swing.JCheckBox ckbRecepBp;
    private javax.swing.JCheckBox ckbRecepOn;
    private javax.swing.JCheckBox ckbRecepOp;
    private javax.swing.ButtonGroup fatorRH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.ButtonGroup tipoSanguineo;
    // End of variables declaration//GEN-END:variables
}
